name: pizza_repository
description: The Repo that handles pizzas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # equatable: ^1.2.5
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2
  # firebase_storage: ^3.1.6
  rxdart: ^0.27.7
  # path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
